### ISSUE TITLE
KPG third meetup

### ISSUE THREAD

**Issue by MoralCode** [KubOS-Preservation-Group/Community#1]
Seems like there was some interest in having another meetup a while ago so heres a poll to see if theres a date in the next two weeks where people are free.

https://lettucemeet.com/l/d85lM

I realize this isnt the most ideal time of year so feel free to leave suggestions if another timeframe would be better

**Comment by patrickoppel** [comment]
I'm on holiday. Happy to sit this one out otherwise I'll be back after Jan 10 and keen to join then

**Comment by elpiel** [comment]
I would love to join the meetup, however, I'm on holiday too.

**Comment by MoralCode** [comment]
Revised the lettucemeet to be the third week of Jan. Link updated in the main issue and also here:

https://lettucemeet.com/l/d85lM

**Comment by MoralCode** [comment]
@patrickwalton i believe you mentioned on our discord that you were interested and wanted an email notification. not sure if this mention will trigger an email or not but worth a shot

**Comment by patrickwalton** [comment]
The mention did trigger an email!

We recently realized we could design our system differently and decided to push back any use of a-scale processors until much later, so I'll have to skip the meetings until I start getting into KubOS later, unfortunately.

**Comment by elpiel** [comment]
I'm a bit occupied with other projects at the moment and I'm not sure I'll be able to join for the current time slots.

I would love to hear/read what you've covered and discussed though!

**Comment by MoralCode** [comment]
i think my current plan is to just revisit many of the ideas from the doc that was created at the last meetup. unless things go off in a unique direction, i probably don't have a ton of unique stuff to add
